// --- DATABASE BAHASA RAKSASA (RIFQYVOXTEXT) ---

// =============================================================================
// LIST 1: BAHASA LENGKAP UNTUK TEKS (135+ Bahasa)
// Format: {code: "kode_api", name: "Bendera Nama Bahasa"}
// =============================================================================
const langTextDB = [
    {code: "id", name: "🇮🇩 Indonesia"},
    {code: "en", name: "🇺🇸 English"},
    {code: "ja", name: "🇯🇵 Japanese"},
    {code: "ko", name: "🇰🇷 Korean"},
    {code: "ar", name: "🇸🇦 Arabic"},
    {code: "zh-CN", name: "🇨🇳 Chinese (Simplified)"},
    {code: "zh-TW", name: "🇹🇼 Chinese (Traditional)"},
    {code: "jv", name: "🇮🇩 Javanese (Jawa)"},
    {code: "su", name: "🇮🇩 Sundanese (Sunda)"},
    {code: "ms", name: "🇲🇾 Malay"},
    {code: "vi", name: "🇻🇳 Vietnamese"},
    {code: "th", name: "🇹🇭 Thai"},
    {code: "hi", name: "🇮🇳 Hindi"},
    {code: "fr", name: "🇫🇷 French"},
    {code: "de", name: "🇩🇪 German"},
    {code: "es", name: "🇪🇸 Spanish"},
    {code: "ru", name: "🇷🇺 Russian"},
    {code: "pt", name: "🇵🇹 Portuguese"},
    {code: "it", name: "🇮🇹 Italian"},
    {code: "nl", name: "🇳🇱 Dutch"},
    {code: "tr", name: "🇹🇷 Turkish"},
    {code: "af", name: "🇿🇦 Afrikaans"},
    {code: "sq", name: "🇦🇱 Albanian"},
    {code: "am", name: "🇪🇹 Amharic"},
    {code: "hy", name: "🇦🇲 Armenian"},
    {code: "as", name: "🇮🇳 Assamese"},
    {code: "ay", name: "🇧🇴 Aymara"},
    {code: "az", name: "🇦🇿 Azerbaijani"},
    {code: "bm", name: "🇲🇱 Bambara"},
    {code: "eu", name: "🇪🇸 Basque"},
    {code: "be", name: "🇧🇾 Belarusian"},
    {code: "bn", name: "🇧🇩 Bengali"},
    {code: "bho", name: "🇮🇳 Bhojpuri"},
    {code: "bs", name: "🇧🇦 Bosnian"},
    {code: "bg", name: "🇧🇬 Bulgarian"},
    {code: "ca", name: "🇪🇸 Catalan"},
    {code: "ceb", name: "🇵🇭 Cebuano"},
    {code: "ny", name: "🇲🇼 Chichewa"},
    {code: "co", name: "🇫🇷 Corsican"},
    {code: "hr", name: "🇭🇷 Croatian"},
    {code: "cs", name: "🇨🇿 Czech"},
    {code: "da", name: "🇩🇰 Danish"},
    {code: "dv", name: "🇲🇻 Dhivehi"},
    {code: "doi", name: "🇮🇳 Dogri"},
    {code: "eo", name: "🌍 Esperanto"},
    {code: "et", name: "🇪🇪 Estonian"},
    {code: "ee", name: "🇬🇭 Ewe"},
    {code: "tl", name: "🇵🇭 Filipino (Tagalog)"},
    {code: "fi", name: "🇫🇮 Finnish"},
    {code: "fy", name: "🇳🇱 Frisian"},
    {code: "gl", name: "🇪🇸 Galician"},
    {code: "ka", name: "🇬🇪 Georgian"},
    {code: "el", name: "🇬🇷 Greek"},
    {code: "gn", name: "🇵🇾 Guarani"},
    {code: "gu", name: "🇮🇳 Gujarati"},
    {code: "ht", name: "🇭🇹 Haitian Creole"},
    {code: "ha", name: "🇳🇬 Hausa"},
    {code: "haw", name: "🇺🇸 Hawaiian"},
    {code: "iw", name: "🇮🇱 Hebrew"},
    {code: "hmn", name: "🇨🇳 Hmong"},
    {code: "hu", name: "🇭🇺 Hungarian"},
    {code: "is", name: "🇮🇸 Icelandic"},
    {code: "ig", name: "🇳🇬 Igbo"},
    {code: "ilo", name: "🇵🇭 Ilocano"},
    {code: "ga", name: "🇮🇪 Irish"},
    {code: "kn", name: "🇮🇳 Kannada"},
    {code: "kk", name: "🇰🇿 Kazakh"},
    {code: "km", name: "🇰🇭 Khmer"},
    {code: "rw", name: "🇷🇼 Kinyarwanda"},
    {code: "gom", name: "🇮🇳 Konkani"},
    {code: "kri", name: "🇸🇱 Krio"},
    {code: "ku", name: "🇹🇷 Kurdish (Kurmanji)"},
    {code: "ckb", name: "🇮🇶 Kurdish (Sorani)"},
    {code: "ky", name: "🇰🇬 Kyrgyz"},
    {code: "lo", name: "🇱🇦 Lao"},
    {code: "la", name: "🇻🇦 Latin"},
    {code: "lv", name: "🇱🇻 Latvian"},
    {code: "ln", name: "🇨🇩 Lingala"},
    {code: "lt", name: "🇱🇹 Lithuanian"},
    {code: "lg", name: "🇺🇬 Luganda"},
    {code: "lb", name: "🇱🇺 Luxembourgish"},
    {code: "mk", name: "🇲🇰 Macedonian"},
    {code: "mai", name: "🇮🇳 Maithili"},
    {code: "mg", name: "🇲🇬 Malagasy"},
    {code: "ml", name: "🇮🇳 Malayalam"},
    {code: "mt", name: "🇲🇹 Maltese"},
    {code: "mi", name: "🇳🇿 Maori"},
    {code: "mr", name: "🇮🇳 Marathi"},
    {code: "mni-Mtei", name: "🇮🇳 Meiteilon (Manipuri)"},
    {code: "lus", name: "🇮🇳 Mizo"},
    {code: "mn", name: "🇲🇳 Mongolian"},
    {code: "my", name: "🇲🇲 Myanmar (Burmese)"},
    {code: "ne", name: "🇳🇵 Nepali"},
    {code: "no", name: "🇳🇴 Norwegian"},
    {code: "or", name: "🇮🇳 Odia (Oriya)"},
    {code: "om", name: "🇪🇹 Oromo"},
    {code: "ps", name: "🇦🇫 Pashto"},
    {code: "fa", name: "🇮🇷 Persian"},
    {code: "pl", name: "🇵🇱 Polish"},
    {code: "pa", name: "🇮🇳 Punjabi"},
    {code: "qu", name: "🇵🇪 Quechua"},
    {code: "ro", name: "🇷🇴 Romanian"},
    {code: "sm", name: "🇼🇸 Samoan"},
    {code: "sa", name: "🇮🇳 Sanskrit"},
    {code: "gd", name: "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scots Gaelic"},
    {code: "nso", name: "🇿🇦 Sepedi"},
    {code: "sr", name: "🇷🇸 Serbian"},
    {code: "st", name: "🇱🇸 Sesotho"},
    {code: "sn", name: "🇿🇼 Shona"},
    {code: "sd", name: "🇵🇰 Sindhi"},
    {code: "si", name: "🇱🇰 Sinhala"},
    {code: "sk", name: "🇸🇰 Slovak"},
    {code: "sl", name: "🇸🇮 Slovenian"},
    {code: "so", name: "🇸🇴 Somali"},
    {code: "sw", name: "🇰🇪 Swahili"},
    {code: "sv", name: "🇸🇪 Swedish"},
    {code: "tg", name: "🇹🇯 Tajik"},
    {code: "ta", name: "🇮🇳 Tamil"},
    {code: "tt", name: "🇷🇺 Tatar"},
    {code: "te", name: "🇮🇳 Telugu"},
    {code: "ti", name: "🇪🇷 Tigrinya"},
    {code: "ts", name: "🇿🇦 Tsonga"},
    {code: "uk", name: "🇺🇦 Ukrainian"},
    {code: "ur", name: "🇵🇰 Urdu"},
    {code: "ug", name: "🇨🇳 Uyghur"},
    {code: "uz", name: "🇺🇿 Uzbek"},
    {code: "cy", name: "🏴󠁧󠁢󠁷󠁬󠁳󠁿 Welsh"},
    {code: "xh", name: "🇿🇦 Xhosa"},
    {code: "yi", name: "🇮🇱 Yiddish"},
    {code: "yo", name: "🇳🇬 Yoruba"},
    {code: "zu", name: "🇿🇦 Zulu"}
];

// =============================================================================
// LIST 2: BAHASA SUARA + DIALEK (Super Lengkap)
// Format: ["Nama Bahasa + Bendera", "Kode_Mic_Browser", "Kode_API_Translate"]
// =============================================================================
const langVoiceDB = [
    // --- INDONESIA & MELAYU ---
    ["🇮🇩 Indonesia", "id-ID", "id"],
    ["🇲🇾 Malay (Malaysia)", "ms-MY", "ms"],
    ["🇮🇩 Javanese (Indonesia)", "jv-ID", "jw"],
    ["🇮🇩 Sundanese (Indonesia)", "su-ID", "su"],

    // --- ENGLISH (Dialek Lengkap) ---
    ["🇺🇸 English (USA)", "en-US", "en"],
    ["🇬🇧 English (UK)", "en-GB", "en"],
    ["🇦🇺 English (Australia)", "en-AU", "en"],
    ["🇨🇦 English (Canada)", "en-CA", "en"],
    ["🇮🇳 English (India)", "en-IN", "en"],
    ["🇳🇿 English (New Zealand)", "en-NZ", "en"],
    ["🇿🇦 English (South Africa)", "en-ZA", "en"],
    ["🇮🇪 English (Ireland)", "en-IE", "en"],
    ["🇵🇭 English (Philippines)", "en-PH", "en"],
    
    // --- ARABIC (Dialek Lengkap) ---
    ["🇸🇦 Arabic (Saudi Arabia)", "ar-SA", "ar"],
    ["🇦🇪 Arabic (UAE)", "ar-AE", "ar"],
    ["🇪🇬 Arabic (Egypt)", "ar-EG", "ar"],
    ["🇰🇼 Arabic (Kuwait)", "ar-KW", "ar"],
    ["🇶🇦 Arabic (Qatar)", "ar-QA", "ar"],
    ["🇯🇴 Arabic (Jordan)", "ar-JO", "ar"],
    ["🇲🇦 Arabic (Morocco)", "ar-MA", "ar"],
    ["🇮🇶 Arabic (Iraq)", "ar-IQ", "ar"],
    ["🇩🇿 Arabic (Algeria)", "ar-DZ", "ar"],
    ["🇹🇳 Arabic (Tunisia)", "ar-TN", "ar"],
    ["🇴🇲 Arabic (Oman)", "ar-OM", "ar"],
    ["🇵🇸 Arabic (Palestine)", "ar-PS", "ar"],

    // --- CHINESE ---
    ["🇨🇳 Chinese (Mandarin - Mainland)", "zh-CN", "zh-CN"],
    ["🇹🇼 Chinese (Taiwan)", "zh-TW", "zh-TW"],
    ["🇭🇰 Chinese (Cantonese)", "zh-HK", "zh-TW"],

    // --- SPANISH (Dialek Lengkap) ---
    ["🇪🇸 Spanish (Spain)", "es-ES", "es"],
    ["🇲🇽 Spanish (Mexico)", "es-MX", "es"],
    ["🇦🇷 Spanish (Argentina)", "es-AR", "es"],
    ["🇨🇴 Spanish (Colombia)", "es-CO", "es"],
    ["🇨🇱 Spanish (Chile)", "es-CL", "es"],
    ["🇵🇪 Spanish (Peru)", "es-PE", "es"],
    ["🇻🇪 Spanish (Venezuela)", "es-VE", "es"],
    ["🇺🇸 Spanish (USA)", "es-US", "es"],
    ["🇪🇨 Spanish (Ecuador)", "es-EC", "es"],
    
    // --- ASIAN ---
    ["🇯🇵 Japanese", "ja-JP", "ja"],
    ["🇰🇷 Korean", "ko-KR", "ko"],
    ["🇹🇭 Thai", "th-TH", "th"],
    ["🇻🇳 Vietnamese", "vi-VN", "vi"],
    ["🇮🇳 Hindi", "hi-IN", "hi"],
    ["🇵🇭 Filipino (Tagalog)", "fil-PH", "tl"],
    ["🇱🇦 Lao", "lo-LA", "lo"],
    ["🇰🇭 Khmer (Cambodia)", "km-KH", "km"],
    ["🇲🇲 Burmese (Myanmar)", "my-MM", "my"],
    ["🇳🇵 Nepali", "ne-NP", "ne"],
    ["🇱🇰 Sinhala", "si-LK", "si"],
    ["🇧🇩 Bengali (Bangladesh)", "bn-BD", "bn"],
    ["🇮🇳 Bengali (India)", "bn-IN", "bn"],
    ["🇮🇳 Gujarati", "gu-IN", "gu"],
    ["🇮🇳 Kannada", "kn-IN", "kn"],
    ["🇮🇳 Marathi", "mr-IN", "mr"],
    ["🇮🇳 Tamil", "ta-IN", "ta"],
    ["🇮🇳 Telugu", "te-IN", "te"],
    ["🇮🇳 Urdu (India)", "ur-IN", "ur"],
    ["🇵🇰 Urdu (Pakistan)", "ur-PK", "ur"],

    // --- EUROPEAN ---
    ["🇫🇷 French (France)", "fr-FR", "fr"],
    ["🇨🇦 French (Canada)", "fr-CA", "fr"],
    ["🇩🇪 German", "de-DE", "de"],
    ["🇮🇹 Italian", "it-IT", "it"],
    ["🇷🇺 Russian", "ru-RU", "ru"],
    ["🇵🇹 Portuguese (Portugal)", "pt-PT", "pt"],
    ["🇧🇷 Portuguese (Brazil)", "pt-BR", "pt"],
    ["🇳🇱 Dutch", "nl-NL", "nl"],
    ["🇹🇷 Turkish", "tr-TR", "tr"],
    ["🇵🇱 Polish", "pl-PL", "pl"],
    ["🇺🇦 Ukrainian", "uk-UA", "uk"],
    ["🇷🇴 Romanian", "ro-RO", "ro"],
    ["🇬🇷 Greek", "el-GR", "el"],
    ["🇭🇺 Hungarian", "hu-HU", "hu"],
    ["🇨🇿 Czech", "cs-CZ", "cs"],
    ["🇸🇪 Swedish", "sv-SE", "sv"],
    ["🇩🇰 Danish", "da-DK", "da"],
    ["🇫🇮 Finnish", "fi-FI", "fi"],
    ["🇳🇴 Norwegian", "no-NO", "no"],
    ["🇸🇰 Slovak", "sk-SK", "sk"],
    ["🇭🇷 Croatian", "hr-HR", "hr"],
    ["🇷🇸 Serbian", "sr-RS", "sr"],
    ["🇧🇬 Bulgarian", "bg-BG", "bg"],
    ["🇨🇦 Catalan", "ca-ES", "ca"],

    // --- AFRICA & OTHERS ---
    ["🇿🇦 Afrikaans", "af-ZA", "af"],
    ["🇰🇪 Swahili (Kenya)", "sw-KE", "sw"],
    ["🇹🇿 Swahili (Tanzania)", "sw-TZ", "sw"],
    ["🇿🇦 Zulu", "zu-ZA", "zu"],
    ["🇮🇱 Hebrew", "he-IL", "iw"],
    ["🇮🇷 Persian (Farsi)", "fa-IR", "fa"]
];
      
